### PR TITLE
flag spark as provided, include sonatype plugin

### PR DESCRIPTION
**Pull request by petz2000**
flag spark as provided, include sonatype plugin

### CODE REVIEW

**Comment by petz2000** [comment]
#3

**Comment by hesserp** [comment]
:+1:

**Comment by aakavalevich** [comment]
👍

**Comment by petz2000** [comment]
👍

**Comment by ovolynets** [comment]
:+1:

**Comment by ovolynets** [comment]
:+1:

**Comment by aakavalevich** [comment]
👍

**Pull request merged**
