### PR TITLE
Use scala 2.12

### PR DESCRIPTION
**Pull request by hesserp**
and update some dependencies

### CODE REVIEW

**Comment by pabair** [comment]
this is a great success

**Comment by pabair** [comment]
👍

**Comment by hesserp** [comment]
:+1:

**Comment by hesserp** [comment]
> this is a great success
@pabair thank you for your enthusiasm, sir

**Comment by hesserp** [comment]
:+1:

**Comment by hesserp** [comment]
:+1:

**Comment by pkosiak** [comment]
👍

**Comment by mjalajel** [comment]
👍

**Comment by hesserp** [comment]
:+1:

**Pull request merged**
